# All values injected via ConfigMap and Secret
spring.application.name=${SPRING_APPLICATION_NAME:reservation-service}
server.port=${SERVER_PORT:8083}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/reservation_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus,metrics}
management.endpoint.prometheus.enabled=${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED:true}
management.metrics.export.prometheus.enabled=${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}
email.service.url=${EMAIL_SERVICE_URL:http://email-notification-service:8090}
spring.autoconfigure.exclude=${SPRING_AUTOCONFIGURE_EXCLUDE:org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration}
