# All values injected via ConfigMap and Secret
spring.application.name=${SPRING_APPLICATION_NAME:service-registry}
server.port=${SERVER_PORT:8761}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:false}
eureka.server.wait-time-in-ms-when-sync-empty=${EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY:0}
