apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: frontend
          image: vivekkpaathak/baratie-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: API_BASE_URL
              value: http://MASTER_PUBLIC_IP:30080
