# Encoded values:
# hotel_user  -> aG90ZWxfdXNlcg==
# Hotel_1234  -> SG90ZWxfMTIzNA==
# root        -> cm9vdA==
# jwt-secret  -> d3VqRXlaZzlXVlVMaUI4QWo2Z1ZaUFF4N1dIS0VWQWZpYURGS0VSV3NYMCs=
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: hotel
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-username: aG90ZWxfdXNlcg==
  mysql-password: SG90ZWxfMTIzNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: hotel
type: Opaque
data:
  jwt-secret: d3VqRXlaZzlXVlVMaUI4QWo2Z1ZaUFF4N1dIS0VWQWZpYURGS0VSV3NYMD0=
