apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: hotel
data:
  SPRING_APPLICATION_NAME: api-gateway
  SERVER_PORT: "8080"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_DISCOVERY_LOCATOR_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
