apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-service-config
  namespace: hotel
data:
  SPRING_APPLICATION_NAME: reservation-service
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reservation_db
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  EMAIL_SERVICE_URL: http://email-notification-service:8090
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_COM_EXAMPLE_RESERVATION_SERVICE: DEBUG
  SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
