apiVersion: v1
kind: ConfigMap
metadata:
  name: roomprice-service-config
  namespace: hotel
data:
  SPRING_APPLICATION_NAME: roomprice-service
  SERVER_PORT: "8094"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/room_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_SHOW_SQL: "false"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
  LOGGING_LEVEL_ROOT: INFO
  LOGGING_LEVEL_COM_EXAMPLE_ROOMPRICE_SERVICE: DEBUG
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus,metrics
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
