apiVersion: v1
kind: ConfigMap
metadata:
  name: service-registry-config
  namespace: hotel
data:
  SPRING_APPLICATION_NAME: service-registry
  SERVER_PORT: "8761"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
  EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY: "0"
