# All values injected via ConfigMap and Secret
spring.application.name=${SPRING_APPLICATION_NAME:staff-service}
server.port=${SERVER_PORT:8087}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/staff_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus,metrics}
management.endpoint.prometheus.enabled=${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED:true}
management.metrics.export.prometheus.enabled=${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:true}
