apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        role: master
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command: ["sh", "-c", "until nc -z service-registry 8761; do echo waiting for eureka; sleep 3; done"]
      containers:
        - name: api-gateway
          image: vivekkpaathak/microservice_project_new-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
