apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  namespace: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      nodeSelector:
        role: worker
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ["sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 3; done"]
        - name: wait-for-eureka
          image: busybox
          command: ["sh", "-c", "until nc -z service-registry 8761; do echo waiting for eureka; sleep 3; done"]
      containers:
        - name: staff-service
          image: vivekkpaathak/microservice_project_new-staff-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: staff-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
